### PR TITLE
Update docker.py

### PR DESCRIPTION
**Pull request by qiukunlong**
The `repository:tag`  maybe like `seqrise.com:5000/clabee/bwa:latest`, which is accepted by docker.  If `sp[1]` doesn't  match valid tag names, it maybe a part of repository. And `if len(sp) == 3` and sp[2]  matches valid tag names, `sp[0]` and `sp[1]` should merged as a repository name

### CODE REVIEW

**Comment by mr-c** [comment]
Hello @qkl871118 , Thank you for your contribution. Can you add a couple test cases to verify your fix?

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by qkl871118** [comment]
Excuse me, how should I add test cases? Describe them here or add some test CWL files to the repository?

**Comment by mr-c** [comment]
@qiukunlong You can add new tests as part of this pull request. See https://github.com/common-workflow-language/cwltool/tree/master/tests

**Pull request merged**
