### PR TITLE
Short circuit google storage schemas during validation.

### PR DESCRIPTION
**Pull request by danbills**
We at the Broad Institute are using cwltool's pre-processing capability.

We have noticed that Google storage links cannot pass the `check_exists` function as they are by nature not publicly accessible.

What I've submitted here is a quick workaround to get over this hurdle.  I've tested it locally and it is working as intended.

One may wonder why we aren't using `schema-salad-tool` directly to do the preprocessing.  We've noticed that `cwltool` seems to handle a larger variety of cases that `schema-salad-tool` does not, however I do not have such comparisons in hand.

We're definitely open to more comprehensive discussion on a parameter to disable this sort of validation (perhaps only applicable during `--print-pre` situations?).

### CODE REVIEW

**Comment by mr-c** [comment]
@danbills If this is part of pre processing, then perhaps the code should be separate from the reference runner?

If we need to refactor to make that more straight forward, then that is fine by me

**Comment by tetron** [comment]
This is patching the wrong thing, it needs to be submitted to https://github.com/common-workflow-language/schema_salad (because the copy of the code here in cwltool is _not_ actually the code used by cwltool)

**Comment by tetron** [comment]
That said, I would be fine with adding an option to schema-salad to specify URI schemes which are opaque but should not generate an error.

**Comment by danbills** [comment]
Closing in favor of a PR to schema salad repo, thanks for your input!

**Pull request closed without merging**
