### PR TITLE
adding warning when default docker container is used on Windows

### PR DESCRIPTION
**Pull request by kapilkd13**
referencing issue #469

### CODE REVIEW

**Comment by kapilkd13** [comment]
@mr-c I need a little help here. We need a test to check that if default container is used on windows, a warning should be given. Although on local system I can test and verify this behavior but since this behavior is `windows with docker` specific, how should we test it in our CI.

**Comment by mr-c** [comment]
No worries, how about a mock object?

https://en.wikipedia.org/wiki/Mock_object

Pe 25 iul. 2017 10:05 p.m., "Kapil kumar" <notifications@github.com> a
scris:

**Comment by kapilkd13** [comment]
Hi @mr-c  I added a test using mock object as suggested by you. That was something new for me. 😄  Can you review it.

**Comment by mr-c** [comment]
Huzzah -- thanks!

**Pull request merged**
