### PR TITLE
[WIP] Hacking on the Userspace Containers idea

### PR DESCRIPTION
**Pull request by kdmurray91**
A standing pull request covering the userspace container ideas discussed in the wiki

### CODE REVIEW

**Comment by mr-c** [comment]
Hey @kdmurray91 I think [udocker](https://github.com/indigo-dc/udocker) fills this role well, so I'm going to close this PR. Thanks for being a trailblazer!

**Comment by kdmurray91** [comment]
@mr-c: Was forwarded this today, are folks here aware of Singularity? https://github.com/singularityware/singularity

**Comment by mr-c** [comment]
@kdmurray91 Yep! @alaindomissy has got it working smoothly with `cwltool` and has shared his experiences a few times on the CWL-HPC calls. I keep bugging him to write up his experiences :-)

Also, Alain has a script to build a Singularity container from a CWL requirements list and has promised to eventually share that as well!

**Comment by mr-c** [comment]
@kdmurray91 Do you mind if I delete this branch?

**Comment by kdmurray91** [comment]
@mr-c done :)

**Pull request closed without merging**
