### PR TITLE
when secondaryFiles is in an array, pass to each item

### PR DESCRIPTION
**Pull request by jeremiahsavage**

### CODE REVIEW

**Comment by jeremiahsavage** [comment]
The fix only works if cwl is draft-2, and causes crash if draft-3. So don't merge.

**Comment by jeremiahsavage** [comment]
Tested successfully with draft-3. I had a bug in cwl test in which I used old style `$self` instead of newer `self`.

**Comment by jeremiahsavage** [comment]
creating new PR which fixes failed check and introduces new test.

**Comment by mr-c** [comment]
New PR is https://github.com/common-workflow-language/cwltool/pull/170

**Pull request closed without merging**
