### PR TITLE
Update print statements to print function calls

### PR DESCRIPTION
**Pull request by tjelvar-olsson**
To make the code more Python 3 compatible.

### CODE REVIEW

**Comment by mr-c** [comment]
cwl-bot, okay to test

**Comment by mr-c** [comment]
Thank you @tjelvar-olsson! I think this is covered by #287, so I'm going to head over there and see what I can do to get it merged.

**Comment by tjelvar-olsson** [comment]
Just noticed that one of the package dependencies "avro" does not seem very Python 3 compliant.  :(

Not sure what the state of the other dependencies are...

**Comment by tjelvar-olsson** [comment]
Thanks for taking the time to merge it.  :)

**Comment by mr-c** [comment]
This was incorporated into #306, thanks!

**Pull request closed without merging**
