### PR TITLE
Add a default None value for dockerimg variable

### LINKED ISSUE #552: UnboundLocalError: local variable 'dockerimg' referenced before assignment
```
.virtualenv/bin/cwltool \
	--enable-ext \
	--outdir results \
	--cachedir cache \
	workflow.cwl \
	job.cwl
.virtualenv/bin/cwltool 1.0.20171017195544
Resolved 'workflow.cwl' to 'file:///home/gijs/prefactor-cwl/workflow.cwl'
[workflow workflow.cwl] start
[step createmap_cal] start
Unexpected exception
Traceback (most recent call last):
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/workflow.py", line 810, in job
    **kwargs):
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 268, in job
    if dockerimg:
UnboundLocalError: local variable 'dockerimg' referenced before assignment
[step createmap_cal] Cannot make job: local variable 'dockerimg' referenced before assignment
[workflow workflow.cwl] completed permanentFail
{
    "mapfile": null
}
Final process status is permanentFail
```

CWL files: https://github.com/gijzelaerr/prefactor-cwl/tree/9bd863af640a75a69342d7a2e890d60cfe15f002

### PR DESCRIPTION
**Pull request by anton-khodak**
Fix #552. Could be merged now, but I am going to add a test for this

### CODE REVIEW

**Comment by anton-khodak** [comment]
Can't reproduce the failure from AppVeyor, the test succeeds on my Windows machine. Any help in confirming whether the problem is in the test itself or AppVeyor configuration would be appreciated.

**Comment by kapilkd13** [comment]
@anton-khodak Currently Appveyor doesn't support docker testing, so we have promptly turned off tests that involves docker on appveyor

**Comment by anton-khodak** [comment]
hey @kapilkd13  , thanks for chiming in! I can't reproduce the failure from AppVeyor, the test succeeds on my Windows machine. It doesn't use a docker image, so I am confused why it fails. Any help in confirming whether the problem is in the test itself or AppVeyor configuration would be appreciated.

**Comment by mr-c** [comment]
@anton-khodak Can you enhance the test to capture & report  the output, not just the return code?

**Comment by mr-c** [comment]
@anton-khodak Thanks. Any execution of a CWL tool under MS Windows requires docker, and hence can't be run on Appveyor. Can you tag this test so that it gets skipped under MS Windows?

**Comment by mr-c** [comment]
Thank you @anton-khodak !

**Pull request merged**
