### PR TITLE
Replace distutils.spawn usage

### LINKED ISSUE #1421: replace distutils.spawn usage
Distutils is deprecated since 2014 and will be removed from the Python standard library in Python 3.12

https://www.python.org/dev/peps/pep-0632/

`distutils.spawn.find_executable` → `shutil.which`
`distutils.spawn.spawn` → `subprocess.run`

https://github.com/common-workflow-language/cwltool/search?q=distutils

### PR DESCRIPTION
**Pull request by KushalBeniwal**
Fix #1421

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Thank you @KushalBeniwal for your contribution!

Can you run `make format` so that the lint checks pass?

**Comment by KushalBeniwal** [comment]
> Can you run make format so that the lint checks pass?

Thanks for the help @mr-c.
Though I'm not sure why the other two tests are failing.

**Comment by mr-c** [comment]
> Though I'm not sure why the other two tests are failing.

This isn't your fault. We are trying to improve having documentation strings in our codebase, and since you edited `tests/test_docker.py` and `tests/test_singularity.py` the `diff_pydocstyle_report` is complaining about the lack of module level docstring.

Maybe you are willing to help us by adding a one line summary of what each file is testing? You can see an example at https://github.com/common-workflow-language/cwltool/blob/main/tests/test_check.py#L1 and https://github.com/common-workflow-language/cwltool/blob/main/tests/test_tmpdir.py#L1

**Comment by KushalBeniwal** [comment]
> Maybe you are willing to help us by adding a one line summary of what each file is testing?

Yes, I will do that.

**Comment by KushalBeniwal** [comment]
@mr-c , I went through the files, `tests/test_docker.py` and `tests/test_singularity.py`, to understand what the functions are doing. I also went through their commit history to understand why they were added in the first place and why some changes were made.

As I wasn't sure how deep I should go in order to know enough about these files, so, can you guide me on further steps or maybe resources I should look into first and please correct me if I'm wrong in my interpretation somewhere or if I'm on the wrong path.

This is what I found,

for `tests/test_singularity.py`,
- "tests to find debian.img in cwd if singularity_pullfolder not in env and to find it in singularity_pullfolder if in env." 
(when `test_singularity_local()` and `test_singularity_pullfolder()` were added).
 Is there something missing?
- The function names were descriptive enough in themselves to get a vague idea on what they might be there for, so, should I go ahead with this and ask for review or should I first look into things more?

for `tests/test_docker.py`,
- "tests for docker mirroring singularity" (when this file was added).
- I saw that the tests in this file were similar to the one's in `tests/singularity.py`. So, should I add something similar to the previous point or something similar to what we'll add for `tests/singularity.py`.

**Comment by KushalBeniwal** [comment]
Thank you @mr-c for your suggestions. I'll add the suggested docstrings in the files.

**Comment by KushalBeniwal** [comment]
Sorry for asking such silly doubts @mr-c but I can't see my new commits in this pull request and I'm also not able to merge your commit.
In this pull request, before last two commits, it's just showing "New commits since you last viewed" and on my git repo which I forked for this pull request it's showing "This branch is 4 commits ahead of common-workflow-language:main." and your commit.

**Comment by mr-c** [comment]
No worries @KushalBeniwal ! Maybe https://docs.github.com/en/github/using-git/getting-changes-from-a-remote-repository will help you?

But the changes are small, so with your permission I can make them here myself. Or if you want to use this as an opportunity to learn more about using git and GitHub I am happy to wait for you.

**Comment by KushalBeniwal** [comment]
> Or if you want to use this as an opportunity to learn more about using git and GitHub I am happy to wait for you.

Thank you @mr-c, I would love to learn more. And if it takes too much time I'll inform you.

**Comment by KushalBeniwal** [comment]
I think I messed up. I'm really sorry for the extra commits.

**Comment by mr-c** [comment]
Thank you @KushalBeniwal ! It is no problem to have extra commits. I used a button GitHub gives to maintainers that squashed the entire pull request into a single commit.

**Comment by KushalBeniwal** [comment]
Thanks @mr-c for all the guidance. I learnt new things working on this issue . 
If you feel like I can work on something else too then please tell.

And I came across type comments in test files, like this, https://github.com/common-workflow-language/cwltool/blob/14c3f8f76c8c7c13ca378b7f1fcd8105fc80b88c/cwltool/docker.py#L31
which can be converted to type hints. I can change them if you want.

**Pull request merged**
