### PR TITLE
Delete intermediate outputs even when they exist

### LINKED ISSUE #892: Output directories containing files don't get cleaned up
## Expected Behavior

cwltool should remove (or have an option to remove) intermediate output directories once they're no longer needed.

## Actual Behavior

Output directories that have files in them (whether that's because the tool generated extra files that weren't included in the output, or because cwltool left the files in place for the next step to use them) are never deleted, meaning that long workflows can consume large amounts of disk and eventually run out of space...

This looks intentional, but I don't understand why it's desirable to leave behind huge numbers of directories containing the output from intermediate steps.

https://github.com/common-workflow-language/cwltool/blob/c27774b2fcfc66497ee22e08b309fd8a542f139b/cwltool/executors.py#L98-L99

https://github.com/common-workflow-language/cwltool/blob/c27774b2fcfc66497ee22e08b309fd8a542f139b/cwltool/process.py#L375-L379

https://github.com/common-workflow-language/cwltool/blob/c27774b2fcfc66497ee22e08b309fd8a542f139b/cwltool/process.py#L799-L801

## Workflow Code

wf.cwl:
```cwl
cwlVersion: v1.0
class: Workflow

inputs:
- id: workflow_input
  type: File

steps:
- id: workflow_step_one
  run: step_one.cwl
  in:
    step_one_input: workflow_input
  out:
  - step_one_output
- id: workflow_step_two
  run: step_two.cwl
  in:
    step_two_input: workflow_step_one/step_one_output
  out:
  - step_two_output

outputs:
- id: workflow_output
  type: File
  outputSource: workflow_step_two/step_two_output
```

step_one.cwl:
```cwl
cwlVersion: v1.0
class: CommandLineTool

baseCommand: ["touch", "step1", "step1_other"]

inputs:
- id: step_one_input
  type: File

outputs:
- id: step_one_output
  type: File
  outputBinding:
    glob: "step1"
```

step_two.cwl:
```cwl
cwlVersion: v1.0
class: CommandLineTool

baseCommand: ["touch", "step2", "step2_other"]

inputs:
- id: step_two_input
  type: File

outputs:
- id: step_two_output
  type: File
  outputBinding:
    glob: "step2"
```

job.yml:
```yaml
workflow_input:
  class: File
  path: input_file # this is just an empty file
```

## Full Traceback

```console
$ cwltool --debug wf.cwl job.yml 
/Users/jh36/venv/bin/cwltool 1.0.20180819175200
Resolved 'wf.cwl' to 'file:///Users/jh36/cwl/tmpfiles/wf.cwl'
[workflow ] initialized from file:///Users/jh36/cwl/tmpfiles/wf.cwl
[workflow ] start
[workflow ] {
    "workflow_input": {
        "class": "File",
        "location": "file:///Users/jh36/cwl/tmpfiles/input_file",
        "size": 11,
        "basename": "input_file",
        "nameroot": "input_file",
        "nameext": ""
    }
}
[workflow ] job step file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_two not ready
[workflow ] starting step workflow_step_one
[job step workflow_step_one] job input {
    "file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_one/step_one_input": {
        "class": "File",
        "location": "file:///Users/jh36/cwl/tmpfiles/input_file",
        "size": 11,
        "basename": "input_file",
        "nameroot": "input_file",
        "nameext": ""
    }
}
[job step workflow_step_one] evaluated job input to {
    "file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_one/step_one_input": {
        "class": "File",
        "location": "file:///Users/jh36/cwl/tmpfiles/input_file",
        "size": 11,
        "basename": "input_file",
        "nameroot": "input_file",
        "nameext": ""
    }
}
[step workflow_step_one] start
[job workflow_step_one] initializing from file:///Users/jh36/cwl/tmpfiles/step_one.cwl as part of step workflow_step_one
[job workflow_step_one] {
    "step_one_input": {
        "class": "File",
        "location": "file:///Users/jh36/cwl/tmpfiles/input_file",
        "size": 11,
        "basename": "input_file",
        "nameroot": "input_file",
        "nameext": ""
    }
}
[job workflow_step_one] path mappings is {
    "file:///Users/jh36/cwl/tmpfiles/input_file": [
        "/Users/jh36/cwl/tmpfiles/input_file",
        "/private/var/folders/9n/vrwpqrl91gl4ft1v0vdghcx0000ggv/T/tmpjk2r7hwx/stg5a3a6b3b-1596-489f-a871-6d6716e98192/input_file",
        "File",
        true
    ]
}
[job workflow_step_one] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "touch"
    },
    {
        "position": [
            -1000000,
            1
        ],
        "datum": "step1"
    },
    {
        "position": [
            -1000000,
            2
        ],
        "datum": "step1_other"
    }
]
[job workflow_step_one] /private/tmp/docker_tmp6dsu5gil$ touch \
    step1 \
    step1_other
[job workflow_step_one] completed success
[job workflow_step_one] {
    "step_one_output": {
        "location": "file:///private/tmp/docker_tmp6dsu5gil/step1",
        "basename": "step1",
        "nameroot": "step1",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[step workflow_step_one] produced output {
    "file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_one/step_one_output": {
        "location": "file:///private/tmp/docker_tmp6dsu5gil/step1",
        "basename": "step1",
        "nameroot": "step1",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[step workflow_step_one] completed success
[job workflow_step_one] Removing input staging directory /private/var/folders/9n/vrwpqrl91gl4ft1v0vdghcx0000ggv/T/tmpjk2r7hwx
[job workflow_step_one] Removing temporary directory /private/var/folders/9n/vrwpqrl91gl4ft1v0vdghcx0000ggv/T/tmpl9_nygt_
[workflow ] starting step workflow_step_two
[job step workflow_step_two] job input {
    "file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_two/step_two_input": {
        "location": "file:///private/tmp/docker_tmp6dsu5gil/step1",
        "basename": "step1",
        "nameroot": "step1",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[job step workflow_step_two] evaluated job input to {
    "file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_two/step_two_input": {
        "location": "file:///private/tmp/docker_tmp6dsu5gil/step1",
        "basename": "step1",
        "nameroot": "step1",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[step workflow_step_two] start
[job workflow_step_two] initializing from file:///Users/jh36/cwl/tmpfiles/step_two.cwl as part of step workflow_step_two
[job workflow_step_two] {
    "step_two_input": {
        "location": "file:///private/tmp/docker_tmp6dsu5gil/step1",
        "basename": "step1",
        "nameroot": "step1",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[job workflow_step_two] path mappings is {
    "file:///private/tmp/docker_tmp6dsu5gil/step1": [
        "/private/tmp/docker_tmp6dsu5gil/step1",
        "/private/var/folders/9n/vrwpqrl91gl4ft1v0vdghcx0000ggv/T/tmpc8es5f5v/stge5b03988-2b54-4b5a-91b2-fa54099e2b7b/step1",
        "File",
        true
    ]
}
[job workflow_step_two] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "touch"
    },
    {
        "position": [
            -1000000,
            1
        ],
        "datum": "step2"
    },
    {
        "position": [
            -1000000,
            2
        ],
        "datum": "step2_other"
    }
]
[job workflow_step_two] /private/tmp/docker_tmpe9ti48xo$ touch \
    step2 \
    step2_other
[job workflow_step_two] completed success
[job workflow_step_two] {
    "step_two_output": {
        "location": "file:///private/tmp/docker_tmpe9ti48xo/step2",
        "basename": "step2",
        "nameroot": "step2",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[step workflow_step_two] produced output {
    "file:///Users/jh36/cwl/tmpfiles/wf.cwl#workflow_step_two/step_two_output": {
        "location": "file:///private/tmp/docker_tmpe9ti48xo/step2",
        "basename": "step2",
        "nameroot": "step2",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[step workflow_step_two] completed success
[workflow ] completed success
[workflow ] {
    "workflow_output": {
        "location": "file:///private/tmp/docker_tmpe9ti48xo/step2",
        "basename": "step2",
        "nameroot": "step2",
        "nameext": "",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}
[job workflow_step_two] Removing input staging directory /private/var/folders/9n/vrwpqrl91gl4ft1v0vdghcx0000ggv/T/tmpc8es5f5v
[job workflow_step_two] Removing temporary directory /private/var/folders/9n/vrwpqrl91gl4ft1v0vdghcx0000ggv/T/tmpk82h0lu3
Moving /private/tmp/docker_tmpe9ti48xo/step2 to /Users/jh36/cwl/tmpfiles/step2
Removing intermediate output directory /private/tmp/docker_tmpzyyjmen_
{
    "workflow_output": {
        "location": "file:///Users/jh36/cwl/tmpfiles/step2",
        "basename": "step2",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "path": "/Users/jh36/cwl/tmpfiles/step2"
    }
}
Final process status is success
$ # these are `JobExecutor.output_dirs`
$ ls /private/tmp/docker_tmpe9ti48xo /private/tmp/docker_tmp6dsu5gil /private/tmp/docker_tmpzyyjmen_
ls: /private/tmp/docker_tmpzyyjmen_: No such file or directory
/private/tmp/docker_tmp6dsu5gil:
step1       step1_other

/private/tmp/docker_tmpe9ti48xo:
step2_other
```

## Your Environment

* cwltool version: 1.0.20180819175200

### PR DESCRIPTION
**Pull request by anowlcalledjosh**
Fixes #892.

The current behaviour goes back to at least cwltool version
1.0.20170723124118.

### CODE REVIEW

**Comment by mr-c** [comment]
Looks like this deletes cached results

**Comment by mr-c** [comment]
Close, but not enough?

https://travis-ci.org/common-workflow-language/cwltool/jobs/425670134#L676

**Comment by anowlcalledjosh** [comment]
mypy doesn't seem to properly propagate the not-None-ness of `cachedir` into lambdas:

```python
if runtime_context.rm_tmpdir:
    cachedir = runtime_context.cachedir
    if cachedir is not None:
        reveal_type(cachedir) # line 102
        (lambda: reveal_type(cachedir) and "foo".startswith(cachedir))() # line 103
```

```console
$ MYPYPATH=typeshed/3:typeshed/2and3 mypy cwltool/executors.py
cwltool/executors.py:102: error: Revealed type is 'builtins.str'
cwltool/executors.py:103: error: Revealed type is 'Union[builtins.str, None]'
cwltool/executors.py:103: error: Argument 1 to "startswith" of "str" has incompatible type "Optional[str]"; expected "Union[str, Tuple[str, ...]]"
```

**Comment by mr-c** [comment]
Huh. How about `assert cachedir is not None` after the `if`?

**Comment by anowlcalledjosh** [comment]
Nope, same behaviour. I refactored it a bit, and it seems to get the types right now...

**Comment by mr-c** [comment]
Thank you @anowlcalledjosh !

**Comment by WEClarke** [comment]
For me this still leaves intermediate directories using the example in [#892](
https://github.com/common-workflow-language/cwltool/issues/892). 

First issue: output_dirs is always empty at L104 in my tests

[https://github.com/common-workflow-language/cwltool/blob/e4bc1021ef406aff98fe68b1d29edb78eaf72c95/cwltool/executors.py#L98-L104](https://github.com/common-workflow-language/cwltool/blob/e4bc1021ef406aff98fe68b1d29edb78eaf72c95/cwltool/executors.py#L98-L104)

Second issue: job_dir is created using tmp_outdir_prefix but also does not get deleted. I tried setting L729 to `shutil.rmtree(job_dir, True)` without success.

[https://github.com/common-workflow-language/cwltool/blob/e4bc1021ef406aff98fe68b1d29edb78eaf72c95/cwltool/job.py#L728-L729](https://github.com/common-workflow-language/cwltool/blob/e4bc1021ef406aff98fe68b1d29edb78eaf72c95/cwltool/job.py#L728-L729)


My solutions are pretty naive but I am including them anyways.

Issue 1: I have moved the creation of the job_dir outside of the call to `_job_popen` and then called for its removal with the other temporary directories.

[https://github.com/WEClarke/cwltool/blob/042902254882d96109f93b5291452626ee6f83f8/cwltool/job.py#L294-L306](https://github.com/WEClarke/cwltool/blob/042902254882d96109f93b5291452626ee6f83f8/cwltool/job.py#L294-L306)

[https://github.com/WEClarke/cwltool/blob/042902254882d96109f93b5291452626ee6f83f8/cwltool/job.py#L385-L389](https://github.com/WEClarke/cwltool/blob/042902254882d96109f93b5291452626ee6f83f8/cwltool/job.py#L385-L389)

Issue 2: I have just used `output_dirs = self.output_dirs` for both cases, knowing that I must be missing something. However, I have tested this with and without --cachedir without issue.

[https://github.com/WEClarke/cwltool/blob/042902254882d96109f93b5291452626ee6f83f8/cwltool/executors.py#L98-L105](https://github.com/WEClarke/cwltool/blob/042902254882d96109f93b5291452626ee6f83f8/cwltool/executors.py#L98-L105)

**Comment by mr-c** [comment]
Thank you @WEClarke for the report. I copied your comment to https://github.com/common-workflow-language/cwltool/issues/951 so we keep track of it

**Pull request merged**
