### PR TITLE
feat(docker-net-option): Allows user to define the docker network

### PR DESCRIPTION
**Pull request by kmhernan**
Instead of `--enable_net` being a boolean, I added the ability to explicitly define the docker network id. If I wanted to use, say, the `host` docker network:

```
cwltool.py --enable-net host ...
```

If you don't use the option is acts just as before.

### CODE REVIEW

**Comment by mr-c** [comment]
add to testlist

**Comment by mr-c** [comment]
Hey Kyle, it is nice to see you here.

I think you want to move from our current two outcome support of `--net=none` or nothing specified to a three outcome situation: `--net=none`, `--net=custom-thingy`, or nothing specified. However this implementation is lacking support for the default networking option.

Can you add that back in?

**Comment by kmhernan** [comment]
Thanks :-). Hmm.. I think understand what you are saying. But I'm not sure what the best implementation would be? I could keep `--enable-net` working like it has been, and add another option to specify the network name for my case, but then it would probably need to a be a mutually exclusive option? If, I try something like:

```
parser.add_argument("--enable-net", const=True, nargs="?", default=False, help="Blah blah..")
```

You could theoretically use `--enable_net` with no value and it would act as it did before, and if you pass a value it could add my functionality; however, I'm not sure if that plays nicely with the positionals in the argparser?? Am I misunderstanding? Thoughts?

**Comment by mr-c** [comment]
Does https://github.com/common-workflow-language/cwltool/commit/a42ef0604e1957c8c91fde26a2f939444df5009b work for you?

**Comment by kmhernan** [comment]
Awesome! Yup. Thanks

**Comment by mr-c** [comment]
@kmhernan Feel free to pull that commit into this PR. I'd like @tetron to review this before we merge.

**Comment by kmhernan** [comment]
@mr-c I believe I just did. Thanks!

**Comment by mr-c** [comment]
Great, thanks @kmhernan !

**Comment by kmhernan** [comment]
@mr-c it looks like there is one line of code missing [#L607](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/main.py#L607) that does not pass the `custom_net` argument to the kwargs of the executor!

**Pull request merged**
