### PR TITLE
start using Py23 schema salad

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by manu-chroma** [comment]
I'm a little confused how ``mypy`` is passing. Because it shouldn't

**Comment by mr-c** [comment]
Looks like it isn't catching the new version https://travis-ci.org/common-workflow-language/cwltool/jobs/247916203#L180

**Comment by manu-chroma** [comment]
maybe restarting build might help?

**Comment by mr-c** [comment]
It's because 2.5.1.2017… is less than 2.5.2017…. :-P Mea culpa! I'll bump the schema-salad version to 2.6 and make a new release

**Comment by manu-chroma** [comment]
haha. good catch

**Comment by manu-chroma** [comment]
@mr-c am I allowed to push in this branch? I will add ``mypy.ini`` file. 

also, regarding unit tests fail, seems like we need to bump ``typing`` package requirement.

**Comment by mr-c** [comment]
@manu-chroma please do

**Pull request merged**
