### PR TITLE
GA4GH task execution API backend

### PR DESCRIPTION
**Pull request by adamstruck**
I wanted to start a dialogue about this work and hear this groups opinion on if this is a logical home for it or if it is better suited in its own project.  Currently it passes all conformance tests with the exception of `[72] Test writable staged files.` TES treats all input file as read-only.  

I wrote a quick python test wrapper around the conformance tests, but ran into problems adding that to the travisci build since it uses both a python 2.7 and 3.5 environment. `cwltest` seems to only support python 2.7. 

Additionally, I updated the `cwltool/schemas` subdirectory to catch up with https://github.com/common-workflow-language/common-workflow-language.  I am not 100% sure what this is used for, but would it make sense to switch this to a git submodule to keep it in sync?

# GA4GH CWL Task Execution 

___cwltool-tes___ submits your tasks to a TES server. Task submission is parallelized when possible. 

[Funnel](https://ohsu-comp-bio.github.io/funnel) is an implementation of the [GA4GH task execution API](https://github.com/ga4gh/task-execution-schemas). It runs your dockerized tasks on htcondor, google compute engine, etc.

## Requirements

* Python 2.7

* [Docker](https://docs.docker.com/)

* [Funnel](https://ohsu-comp-bio.github.io/funnel)

## Quickstart

* Start the task server

```
funnel server
```

* Run your CWL tool/workflow

```
TMPDIR=./ ./cwltool-tes --tes http://localhost:8000 tests/hashsplitter-workflow.cwl.yml --input tests/resources/test.txt
```

## Install

To install from source:

```
python setup.py install
```

## Run the v1.0 conformance tests

To start a funnel server instance automatically and run all of the conformance tests:

```
nosetests -w ./tests
```

_A more manual approach:_

Start the funnel server.

```
funnel server --config /path/to/config.yaml
```

Make sure that TMPDIR is specified in the AllowedDirs of your Local storage configuration.

Run the tests.

```
./tests/run_conformance.sh
```

### CODE REVIEW

**Comment by mr-c** [comment]
Hey @adamstruck , this is really cool!

It should probably be in a separate repository, yes. I've created https://github.com/common-workflow-language/cwl-tes and added you as a repository admin there.

When you're ready for some publicity, please open a PR against https://github.com/common-workflow-language/common-workflow-language/blob/master/README.md#implementations 

Please let me know how else I can be of assistance!

**Comment by adamstruck** [comment]
Thanks @mr-c! Could you provide me some guidance on how to integrate with the Jenkins instance that runs the conformance tests?

**Comment by mr-c** [comment]
You are welcome @adamstruck 
Normally we use [`run_test.sh --junit-xml=result.xml`](https://github.com/common-workflow-language/common-workflow-language/blob/master/run_test.sh) perhaps with `RUNNER=cwltool-tes` in this case. If you need anything else setup prior (and any clean up after) then I'll need to know that as well.

**Comment by mr-c** [comment]
Looks like the `funnel` server will need launching on a random, unused port, and that port will need to be passed to `run_test.sh` via `EXTRA=--tes http://localhost:port_number_here`, yes?

**Pull request closed without merging**
