### PR TITLE
remove draft-2 and draft-3 support

### PR DESCRIPTION
**Pull request by manu-chroma**
Closes 

Issues related to drafts: https://github.com/common-workflow-language/cwltool/issues/119, https://github.com/common-workflow-language/cwltool/issues/441, https://github.com/common-workflow-language/cwltool/issues/431

### CODE REVIEW

**Comment by manu-chroma** [comment]
I believe a major chunk of ``update.py`` should also be removed, update methods like:  
```
_draft2toDraft3dev1
_draftDraft3dev3toDev4
```
https://github.com/common-workflow-language/cwltool/blob/master/cwltool/update.py#L49

Also, we do not intend to deprecate ``draft-4`` at this moment?

**Comment by manu-chroma** [comment]
In reference to this: https://github.com/common-workflowlanguage/cwltool/blob/master/cwltool/update.py#L542

Does this mean ``draft-2`` and ``draft-3`` should still work when using ``--enable-dev`` flag.

**Comment by mr-c** [comment]
Correct, draft-4 should also be removed.  `--enable-dev` will only enable `v1.1.0-dev1` after this is done

**Comment by manu-chroma** [comment]
Just realised, ``tool`` is a common variable and is already used in ``main.py``. 

Can we have a more unique rename for the file ``draf2tool.py``?
@mr-c @tetron

**Comment by mr-c** [comment]
`cltool`?

**Comment by manu-chroma** [comment]
Tests passing again :smile:

**Comment by manu-chroma** [comment]
@mr-c Can you help me with Jenkins build error? 
https://ci.commonwl.org/job/cwltool-pr-conformance-multiver/744/console

Not sure if occurred due to force push or anything else.

**Comment by mr-c** [comment]
I made a simple commit to force a new build

**Comment by mr-c** [comment]
What's the change in code coverage?

**Comment by manu-chroma** [comment]
Roughly ``2%`` increase from the [last time I posted](https://github.com/common-workflow-language/cwltool/issues/334#issuecomment-309292744). 

```
Name                               Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------
cwltool/__init__.py                    2      0      0      0   100%
cwltool/__main__.py                    4      4      0      0     0%
cwltool/builder.py                   190     54    126     20    65%
cwltool/cltool.py                    475    146    246     44    64%
cwltool/cwlrdf.py                     84     33     38     11    54%
cwltool/docker.py                     99     85     52      0     9%
cwltool/docker_id.py                  46     32     10      1    27%
cwltool/draft2tool.py                  3      3      0      0     0%
cwltool/errors.py                      4      0      0      0   100%
cwltool/expression.py                174     29    100     16    78%
cwltool/factory.py                    32      1      4      1    94%
cwltool/flatten.py                    19      5     10      3    72%
cwltool/job.py                       314    143    176     26    49%
cwltool/load_tool.py                 144     33     90     18    72%
cwltool/main.py                      560    175    248     63    64%
cwltool/mutation.py                   37      3      8      3    87%
cwltool/pack.py                      125     17    106      7    84%
cwltool/pathmapper.py                175     21     92     14    83%
cwltool/process.py                   548    136    330     44    70%
cwltool/resolver.py                   40     30     18      0    17%
cwltool/sandboxjs.py                 211    119     94     12    41%
cwltool/software_requirements.py      74     53     26      0    21%
cwltool/stdfsaccess.py                51      7     14      0    83%
cwltool/update.py                    119     90     60      0    16%
cwltool/utils.py                     104     54     60      8    46%
cwltool/workflow.py                  635    148    384     45    75%
--------------------------------------------------------------------
TOTAL                               4269   1421   2292    336    63%
```

**Comment by manu-chroma** [comment]
@mr-c Can you address this [issue](https://github.com/common-workflow-language/cwltool/issues/119#issuecomment-321996977)?

**Comment by manu-chroma** [comment]
@tetron Can you review?

**Comment by anton-khodak** [comment]
@mr-c ready to be merged!

**Pull request merged**
