### PR TITLE
Fixing workflow default behavior

### PR DESCRIPTION
**Pull request by kellrott**
Fix for https://github.com/common-workflow-language/cwltool/issues/592

### CODE REVIEW

**Comment by mr-c** [comment]
Thank you @kellrott ! I'll merge this once we have a conformance test demonstrating the error

**Comment by kellrott** [comment]
Conformance test added: https://github.com/common-workflow-language/common-workflow-language/pull/585

**Comment by tetron** [comment]
jenkins, test this please

**Comment by kellrott** [comment]
Thanks for the merge. Any idea when a new release will get pushed to pypi?

**Comment by tetron** [comment]
I have one other branch I want to merge and then I can do a new release, so hopefully tomorrow.

**Comment by kellrott** [comment]
Thank you. I'm working on a publication, and the CWL workflows are part of the materials/methods. This is a bit of a blocker.

**Comment by mr-c** [comment]
@kellrott I can release right now if that is okay with @tetron

**Comment by kellrott** [comment]
I can wait till tomorrow

**Comment by tetron** [comment]
@kellrott  you're all set: 1.0.20180108222053

**Comment by kellrott** [comment]
Awesome, thanks.

**Pull request merged**
