### PR TITLE
[wip] simple input object generation

### PR DESCRIPTION
**Pull request by mr-c**
Inspired by Dockstore's equivalent feature 

Will close https://github.com/common-workflow-language/cwltool/issues/384

### CODE REVIEW

**Comment by ctb** [comment]
Note that 

```
cwltool --make-template https://github.com/CancerCollaboratory/dockstore-tool-bamstats/raw/develop/Dockstore.cwl > params.yaml
```

succeeds but shows the following error message that made me think it did not succeed:

```
/home/tx160085/env/bin/cwltool 1.0
https://github.com/CancerCollaboratory/dockstore-tool-bamstats/raw/develop/Dockstore.cwl:3:1: unrecognized extension field `http://purl.org/dc/terms/creator`.  Did you include a $schemas section?
```

Any way to change this to a warning, or be more verbose about the fact that params.yml is legit?

**Comment by ctb** [comment]
Also - the dockstore output includes a section for the output file, e.g. `bamstats_report` in the example that https://github.com/ngs-docs/2017-cloud-workflows-misc/pull/1 is modifying. This doesn't seem to be the case with the `--make-template` command. Is that what you mean in [this comment](https://github.com/ngs-docs/2017-cloud-workflows-misc/pull/1#issuecomment-314771135) by `uses the standardized --outdir option`? thx!

**Comment by mr-c** [comment]
@ctb thank you for the verification. This is incomplete but I'll release it for later improvement :-)

Re: output file name in the input object -- yes, that is a dockstore specific extension (and one that I never personally understood). Use the standardized `--outdir` if you'd like to put your outputs anywhere besides the current working directory. If you'd like to discover the filename of a particular output you can parse the output JSON to find out (some workflows the file names vary).

**Comment by mr-c** [comment]
re: the warning, this is a known regression https://github.com/common-workflow-language/cwltool/issues/455

**Comment by denis-yuen** [comment]
@ctb @mr-c  FYI, the output file name is for specifying an output location https://dockstore.org/docs/advanced-features#file-provisioning 

Note that putting it in `/tmp` works but is probably a less interesting example than putting the output into S3, Synapse, etc.

**Comment by mr-c** [comment]
@denis-yuen Ah, that makes more sense. It would be more portable if you added these as a `dockstore` specific directives, otherwise it looks like another input which is confusing to CWL runners and humans alike:

Example:
``` yaml
bam_input:
    class: File
    path: /tmp/NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.bam
dockstore:outputs:
    bamstats_report:
        class: File
        path: /tmp/bamstats_report.zip
```

This should be proposed as a standardized optional feature, then `dockstore:outputs` could become `cwl:outputs`

**Comment by denis-yuen** [comment]
@mr-c I think that would be a reasonable improvement. It would simplify our code too.

**Pull request merged**
