### PR TITLE
Allow disabling matching the container user to the running user

### PR DESCRIPTION
**Pull request by denis-yuen**
We're running into an issue where cwltool sets the uid to match the running user overriding the `USER` command https://docs.docker.com/engine/reference/builder/#/user

This pull request proposes an option to disable this setting.

This is further documented at https://github.com/ga4gh/dockstore/issues/475

### CODE REVIEW

**Comment by mr-c** [comment]
Thanks @denis-yuen Does this PR fix it for @brainstorm et al. or is the gid sticky bit trick also needed?

**Comment by brainstorm** [comment]
So far it does! I'm running the pipeline from ga4gh/dockstore#475 and it does not seem to crash as immediately as it did before on the cwltool step.

+1 on merging this I would say.

**Comment by brainstorm** [comment]
No sticky bits or other additions needed AFAICT right now... so ++1 for merge, imho.

**Comment by mr-c** [comment]
Thanks, all!

**Pull request merged**
