### PR TITLE
README: Fix linting and minor errors

### PR DESCRIPTION
**Pull request by manu-chroma**
Closes https://github.com/common-workflow-language/cwltool/issues/401

### CODE REVIEW

**Comment by manu-chroma** [comment]
@mr-c Can you help me with this error? 
```
running check
warning: Check: :206: (WARNING/2) Inline literal start-string without end-string.

warning: Check: Invalid markup which will not be rendered on PyPI.

error: Please correct your package.
```

**Comment by manu-chroma** [comment]
It is rendering correctly when converted to HTML. Also, the error produced is a warning but still returns a failure code.  

image

**Comment by manu-chroma** [comment]
I've a wild proposition to make: Convert current ``rst`` doc to ``markdown`` and have something like this: https://github.com/mr-karan/webkin/blob/master/setup.py#L5 

I will be happy to do this. Editing ``rst`` docs take up just too much time. Your thoughts @mr-c

**Comment by mr-c** [comment]
@manu-chroma When rendering was there a specific error or warning?

**Comment by manu-chroma** [comment]
@no, ``pandoc``directly gave ``HTML`` output. 
Seeing ``pandoc --help``, there does not seem to be any error checking mechanism in place.

**Comment by mr-c** [comment]
I used https://pypi.python.org/pypi/restview and found the formatting errors, just a couple missing spaces

**Comment by manu-chroma** [comment]
> I used pypi.python.org/pypi/restview and found the formatting errors, just a couple missing spaces

Just tried this. Error messages are same as that of ``tox``. @mr-c Can you help me in the fix?

**Comment by mr-c** [comment]
@manu-chroma see my commit :-P

**Comment by mr-c** [comment]
RST needs a space after the ending double backtick of an inline literal: http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup

**Comment by manu-chroma** [comment]
@mr-c Thanks. Missed it in first glance :P

**Pull request merged**
