### PR TITLE
Fix/initialworkdir docker

### PR DESCRIPTION
**Pull request by jeremiahsavage**
Assigns an outdir, and then symlinks an input file to that outdir.

Tested with cwl in https://github.com/common-workflow-language/cwltool/issues/126

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to testlist

**Comment by mr-c** [comment]
@jeremiahsavage Thank you for your PR! Can you add your test case to the repository?

**Comment by kellrott** [comment]
This PR solves some issues that we are having with sample pipelines in the SMC-RNA challenge. What else needs to be done to get this accepted?

**Comment by tetron** [comment]
Tests are failing, suggest merge/rebase on master

**Comment by kellrott** [comment]
Does this patch solve #126 ? I tested it with the example tool, and I'm getting 
```
~/cwltool$ cwltool test.cwl --INPUT README.rst 
/home/ubuntu/cwltool/venv/bin/cwltool 1.0.20160726135535
[job test.cwl] /tmp/tmpKAeacr$ docker \
    run \
    -i \
    --volume=/home/ubuntu/cwltool/README.rst:/var/lib/cwl/stgb097f828-dfd7-46a2-a8ba-dc2c43a04457/README.rst:ro \
    --volume=/tmp/tmpKAeacr:/var/spool/cwl:rw \
    --volume=/tmp/tmpGizd0G:/tmp:rw \
    --workdir=/var/spool/cwl \
    --read-only=true \
    --user=1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/var/spool/cwl \
    alpine \
    touch \
    README.bai
Error while running job: Error collecting output for parameter 'OUTPUT': [Errno 2] No such file or directory: '/tmp/tmpKAeacr/README.rst'
[job test.cwl] completed permanentFail
Final process status is permanentFail
Workflow error, try again with --debug for more information:
  Process status is ['permanentFail']
```

This is after merging in the most recent changes to master with fix/initialworkdir_docker. Maybe these is some conflict?

**Comment by tetron** [comment]
Jenkins, test this please

**Comment by tetron** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
@jeremiahsavage Yeah, the tests still fail and that doesn't appear to be Jenkins's fault.

**Comment by thomasyu888** [comment]
How is this coming along?

**Comment by mr-c** [comment]
@thomasyu888 the merge conflicts need resolving, and the failing tests need to be addressed.

**Comment by jeremiahsavage** [comment]
A simpler fix incoming

**Comment by jeremiahsavage** [comment]
link
https://github.com/common-workflow-language/cwltool/pull/162

**Pull request closed without merging**
