### PR TITLE
--leave-tmpdir includes the input staging directories

### PR DESCRIPTION
**Pull request by mr-c**
found while working with @RenskeW

### CODE REVIEW

**Comment by kinow** [comment]
Sorry the delay. Tested with the example 15 from the user guide. Confirmed the directory is not deleted. Everything looking good! :+1: Thanks

image

```cwltool --leave-tmpdir linkfile.cwl arguments-job.yml```

**Comment by ltirrell** [comment]
wanted to bump this and see if it could be merged. it really helps with debugging and checking intermediate steps in workflows

**Comment by ltirrell** [comment]
sorry for another comment, but is there anything holding this back from being merged?

**Comment by kinow** [comment]
> sorry for another comment, but is there anything holding this back from being merged?

I think something changed in the commits after I tested it. CI builds are failing now.

**Comment by mr-c** [comment]
GitHub Actions and other things are broken https://www.githubstatus.com/incidents/pr3498h3qkfy

**Pull request merged**
