### PR TITLE
Added fix for detecting with singularity --userns is broken

### PR DESCRIPTION
**Pull request by pvanheus**
Uses a real (4127 byte) singularity container to test if `--userns` works. This is a fix for #764.

### CODE REVIEW

**Comment by pvanheus** [comment]
Does that codecov patch imply that the `singularity.py` code is not tested enough?

**Comment by mr-c** [comment]
Jenkins, add to test list

**Comment by mr-c** [comment]
I think lines 32-38 from https://github.com/boutiques/boutiques/pull/251/files#diff-354f30a63fb0907d4ad57269548329e3R32 should be sufficient to install Singularity in TravisCI

Do you want to add it, or shall I?

**Comment by mr-c** [comment]
Jenkins, add to testlist

**Pull request merged**
