### PR TITLE
removing python 3 status from windows documentation

### PR DESCRIPTION
**Pull request by kapilkd13**
references #499 
with python 3 on windows we use `past` module to use python 2 implementation of  `avro`. This module has reference to `/tmp/..` hardcoded in it.  Thus it need `/tmp` folder in the windows current Drive's root. So I think its best to hold python 3 support from windows docs for now.

### CODE REVIEW

**Comment by manu-chroma** [comment]
@kapilkd13 I feel this is a trivial fix and we should let Python 3 support be there. I've created a WIP Patch in ``schema_salad`` repo: https://github.com/common-workflow-language/schema_salad/pull/125

@mr-c What's your take on this one? More info on: #499

**Comment by kapilkd13** [comment]
@manu-chroma It was a temporary fix. I would delete it once your PR gets merged. I can test your PR tomorrow morning on windows if you want.

**Comment by mr-c** [comment]
Lets confirm and merge ASAP -- the upstream reporting checklist has been moved to https://github.com/common-workflow-language/schema_salad/issues/126

**Comment by mr-c** [comment]
Whoops, I commented in the wrong place. I'm closing this is favor of https://github.com/common-workflow-language/schema_salad/pull/125

**Pull request closed without merging**
