### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by gijzelaerr**
* Remove unused imports
 * Fix indentation / remove tabs
 * Fix various pep8 errors and warnings
 * Resolve various static code analysis warnings

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to testlist

**Comment by mr-c** [comment]
@gijzelaerr This is great, thanks!Since ` cwltool/schemas/` is an git subtree from the specification, and that in turn contains several git subtrees from the schema_salad repo, can you exclude that whole folder from this PR?

**Comment by mr-c** [comment]
Also, it looks like your cleanups disagree with our `flake8` settings: https://travis-ci.org/common-workflow-language/cwltool/jobs/199521865#L185

**Comment by gijzelaerr** [comment]
done!

**Pull request merged**
