### PR TITLE
Removed unused stepname in check_adjust 

### PR DESCRIPTION
**Pull request by tetron**

### CODE REVIEW

**Comment by tetron** [comment]
Yes, that's a good idea.  That's going to take a little longer, though.

**Comment by kapilkd13** [comment]
Hi, I am trying to create test for `check_adjust`, and I am little confused on how to obtain input to be passed to this function. I have created a base model for unit test here. https://gist.github.com/kapilkd13/70e53c79703611e678f2ab29f7189d5e Please have a look and tell if I am going in right direction. Thanks

**Comment by mr-c** [comment]
@kapilkd13 I think the bigger issue is that there is no test that involved `--cachedir` -- even a simple invocation would have caught this bug

**Comment by kapilkd13** [comment]
You are right. We should actually create a test case  for `--cachedir` and other arguments.

**Comment by mr-c** [comment]
I can confirm this fix, thank you @tetron

**Pull request merged**
