### PR TITLE
No useless dirs

### PR DESCRIPTION
**Pull request by tetron**
* Fix long standing bug creating useless empty temp directories, cluttering up user's filesystem
* Fix correctness issue getting `loadListing` from `outputBinding`.

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Oh, I was looking at something similar; this makes a lot more sense. Can we get some tests as well?

**Comment by tetron** [comment]
The `loadListing` bugfix definitely needs a conformance test.

This business with creating useless output directories is a little harder to test for.  Maybe it could run a workflow and then check that there are no unexpected directories left over.

**Comment by tetron** [comment]
https://github.com/common-workflow-language/cwl-v1.2/pull/69

**Comment by mr-c** [comment]
Oops, guess I need to tweak the mergify config

**Pull request merged**
