### PR TITLE
adds a --cache-net-dir option to the tool to store requested schemas on disk if specified

### PR DESCRIPTION
**Pull request by hmenager**

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to testlist
Pe 17 iun. 2016 2:42 p.m., "Common Workflow Language project bot" <
notifications@github.com> a scris:

**Comment by tetron** [comment]
@hmenager the schema loading actually happens in schema salad.  Would you be able to implement this feature in schema salad instead of cwltool?

**Comment by hmenager** [comment]
@tetron I'm not sure I can, but I will try and ask for help if needed.

**Comment by tetron** [comment]
File and schema caching should be addressed in this merge https://github.com/common-workflow-language/schema_salad/pull/49

**Comment by mr-c** [comment]
Thank you @hmenager for this!

**Pull request closed without merging**
