### PR TITLE
[MRG] turn on Python 3 on travis CI

### PR DESCRIPTION
**Pull request by manu-chroma**

### CODE REVIEW

**Comment by manu-chroma** [comment]
for this to work, we'll need to make a new ``schema_salad`` release which uses ``avro-cwl`` for Python 3

**Comment by manu-chroma** [comment]
this one looks baked. @mr-c can you review?

**Comment by manu-chroma** [comment]
also, how to go about running conformance tests for python 3 in jenkins?

**Comment by mr-c** [comment]
@manu-chroma  https://github.com/common-workflow-language/cwltool/pull/465 :-)

**Comment by manu-chroma** [comment]
@mr-c should we merged this one before @kapilkd13 windows branch or after that one?

I might iterate some of the ``mypy`` annotations over time but this one can be merged for the time being.

**Comment by mr-c** [comment]
I'm happy to merge whoever is ready first. This looks ready to me -- what do you think?

**Comment by manu-chroma** [comment]
@mr-c, I can make separate PR for any further improvements. Since this one has lesser number of changes, we can get this one merged first.

**Comment by manu-chroma** [comment]
FWIW, I've created this PR on avro repository and provided brief description for doing the same: https://github.com/apache/avro/pull/235

As discussed before, using something like this failed because ``autotranslate`` anyways tried to convert all the blocks and failed.  
``` python
if sys.version_info.major >= 3:
   # do something
else:
    # something else
```

**Pull request merged**
