### PR TITLE
Add helpful error message when a program is terminated by a (Unix) signal, such as a segfault

### LINKED ISSUE #580: Add helpful error message when a program is terminated by a (Unix) signal, such as a segfault
Currently one gets a error as the expected outputs are not available, which is technically true but unhelpful.

- [ ] Add helpful error message for [return code 139](https://stackoverflow.com/questions/14599670/what-error-code-does-a-process-that-segfaults-return)
- [ ] Add a test for this behaviour

Thanks to @gijzelaerr  for the idea

### PR DESCRIPTION
**Pull request by gmloose**
Fixes #580

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Thanks!

**Review by mr-c — CHANGES_REQUESTED** [review]
`make format` should clean up the linting issue

You can also run `tox` locally to duplicate what the CI does

**Comment by gmloose** [comment]
> `make format` should clean up the linting issue

Done and pushed new commit.

**Comment by gmloose** [comment]
I'm confused by the message from codecov[bot]. How can this small addition cause a drop in coverage of 16.16% and affect over 60 files :confused:

**Comment by mr-c** [comment]
> I'm confused by the message from codecov[bot]. How can this small addition cause a drop in coverage of 16.16% and affect over 60 files 😕

It is because the first CI run failed. That comment will update as the CI completes

**Comment by mr-c** [comment]
> [The diff coverage is 100.00%.](https://github.com/common-workflow-language/cwltool/pull/1569#issuecomment-977700551)

Congratulations! I'm surprised, though. I didn't know we had a test that is terminated by a POSIX signal

**Review by mr-c — APPROVED** [review]

**Pull request merged**
