### PR TITLE
Add rdfs namespaces where used in Process.yml and Workflow.yml

### PR DESCRIPTION
**Pull request by MarkRobbo**
Possible fix for #427

### CODE REVIEW

**Comment by mr-c** [comment]
Thanks!

```
Tool definition failed initialization:
https://w3id.org/cwl/CommonWorkflowLanguage.yml:11:3: Syntax error while parsing a block mapping
https://w3id.org/cwl/CommonWorkflowLanguage.yml:11:3:   in "https://w3id.org/cwl/Workflow.yml", line 4, column 3
https://w3id.org/cwl/CommonWorkflowLanguage.yml:11:3: expected <block end>, but found '<scalar>'
https://w3id.org/cwl/CommonWorkflowLanguage.yml:11:3:   in "https://w3id.org/cwl/Workflow.yml", line 9, column 10
```

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
@MarkRobbo the `schemas` directory is a git sub tree from https://github.com/common-workflow-language/common-workflow-language -- can you make a PR there?

**Comment by MarkRobbo** [comment]
common-workflow-language/common-workflow-language#461

**Pull request closed without merging**
