### PR TITLE
Fix #628 and improve parameter reference error messages

### LINKED ISSUE #648: Expression-like valid javascript fails
Running the command line tool:

```yaml
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo

requirements:
  - class: InlineJavascriptRequirement
inputs:
  - id: parameter
    inputBinding:
      valueFrom: $(true)
    type: string?

outputs: []
```

Fails:

```
/usr/local/bin/cwltool 1.0.20180130110340
Resolved '../../workflows/test.cwl' to 'file:///Users/th10/checkouts/arvados-pipeline/arvados-pipelines/cwl/workflows/test.cwl'
Parsed job order from command line: {
    "id": "../../workflows/test.cwl",
    "parameter": null
}
[job test.cwl] initializing from file:///Users/th10/checkouts/arvados-pipeline/arvados-pipelines/cwl/workflows/test.cwl
[job test.cwl] {
    "parameter": null
}
[job test.cwl] path mappings is {}
[job test.cwl] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "echo"
    },
    {
        "valueFrom": "$(true)",
        "position": [
            0,
            "parameter"
        ],
        "datum": null
    }
]
Workflow error, try again with --debug for more information:
../../workflows/test.cwl:10:7: Traceback (most recent call last):
                               
                                 File
                                 "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line
                                 163, in evaluator
                                   return next_seg(m.group(0)[m.end(1) - m.start(0):-1],
                                   obj[m.group(1)])
                               
                               KeyError: 'true'
                               
                               
                               During handling of the above exception, another exception occurred:
                               
                               
                               Traceback (most recent call last):
                               
                                 File
                                 "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line
                                 234, in do_eval
                                   js_console=js_console)
                               
                                 File
                                 "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line
                                 187, in interpolate
                                   debug=debug, js_console=js_console)
                               
                                 File
                                 "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line
                                 165, in evaluator
                                   raise WorkflowException("%s%s" % (m.group(1), w))
                               
                               cwltool.errors.WorkflowException: true'true'
                               
                               
                               During handling of the above exception, another exception occurred:
                               
                               
                               Traceback (most recent call last):
                               
                                 File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py",
                                 line 211, in generate_arg
                                   value = self.do_eval(binding["valueFrom"], context=value)
                               
                                 File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py",
                                 line 263, in do_eval
                                   force_docker_pull=self.force_docker_pull)
                               
                                 File
                                 "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line
                                 237, in do_eval
                                   raise WorkflowException("Expression evaluation error:\n%s" % e)
                               
                               cwltool.errors.WorkflowException: Expression evaluation error:
                               true'true'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 163, in evaluator
    return next_seg(m.group(0)[m.end(1) - m.start(0):-1], obj[m.group(1)])
KeyError: 'true'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 234, in do_eval
    js_console=js_console)
  File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 187, in interpolate
    debug=debug, js_console=js_console)
  File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 165, in evaluator
    raise WorkflowException("%s%s" % (m.group(1), w))
cwltool.errors.WorkflowException: true'true'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py", line 211, in generate_arg
    value = self.do_eval(binding["valueFrom"], context=value)
  File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py", line 263, in do_eval
    force_docker_pull=self.force_docker_pull)
  File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 237, in do_eval
    raise WorkflowException("Expression evaluation error:\n%s" % e)
cwltool.errors.WorkflowException: Expression evaluation error:
true'true'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 976, in main
    **vars(args))
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 291, in single_job_executor
    for r in jobiter:
  File "/usr/local/lib/python3.6/site-packages/cwltool/draft2tool.py", line 500, in job
    j.command_line = flatten(list(map(builder.generate_arg, builder.bindings)))
  File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py", line 211, in generate_arg
    value = self.do_eval(binding["valueFrom"], context=value)
  File "/usr/local/lib/python3.6/site-packages/schema_salad/sourceline.py", line 155, in __exit__
    raise self.makeError("\n".join(traceback.format_exception(exc_type, exc_value, tb)))
cwltool.errors.WorkflowException: ../../workflows/test.cwl:10:7: Traceback (most recent call last):
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 163, in evaluator
../../workflows/test.cwl:10:7:     return next_seg(m.group(0)[m.end(1) - m.start(0):-1], obj[m.group(1)])
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: KeyError: 'true'
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: During handling of the above exception, another exception occurred:
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: Traceback (most recent call last):
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 234, in do_eval
../../workflows/test.cwl:10:7:     js_console=js_console)
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 187, in interpolate
../../workflows/test.cwl:10:7:     debug=debug, js_console=js_console)
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 165, in evaluator
../../workflows/test.cwl:10:7:     raise WorkflowException("%s%s" % (m.group(1), w))
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: cwltool.errors.WorkflowException: true'true'
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: During handling of the above exception, another exception occurred:
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: Traceback (most recent call last):
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py", line 211, in generate_arg
../../workflows/test.cwl:10:7:     value = self.do_eval(binding["valueFrom"], context=value)
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/builder.py", line 263, in do_eval
../../workflows/test.cwl:10:7:     force_docker_pull=self.force_docker_pull)
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7:   File "/usr/local/lib/python3.6/site-packages/cwltool/expression.py", line 237, in do_eval
../../workflows/test.cwl:10:7:     raise WorkflowException("Expression evaluation error:\n%s" % e)
../../workflows/test.cwl:10:7: 
../../workflows/test.cwl:10:7: cwltool.errors.WorkflowException: Expression evaluation error:
../../workflows/test.cwl:10:7: true'true'
```

This is because this javascript expression is being evaluated as a CWL expression and failing here: https://github.com/common-workflow-language/cwltool/blob/52c276d1a384bed977f2355513f1c07a66b11971/cwltool/expression.py#L165 A fix for this is to fall back to parsing the expression as JavaScript if it fails to be parsed as a CWL expression - I'll have a look at making a pull request with this in.

### PR DESCRIPTION
**Pull request by ThomasHickman**
This fixes #648 and makes the error messages for parameter references better (as referenced in the commit). I've also cleaned up the code which I've changed, to make it easier for other people to edit.

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to test list

**Comment by mr-c** [comment]
Jenkins, add to testlist

**Comment by mr-c** [comment]
Running this with the example file from https://github.com/common-workflow-language/cwltool/issues/648#issue-295502575
```
$ cwltool --validate expr_fail.cwl 
/home/michael/cwltool/env/bin/cwltool 1.0.20180210112813
/home/michael/cwltool/env/bin/cwltool 1.0.20180210112813
Resolved 'expr_fail.cwl' to 'file:///home/michael/cwltool/expr_fail.cwl'
Resolved 'expr_fail.cwl' to 'file:///home/michael/cwltool/expr_fail.cwl'
Tool definition is valid
Tool definition is valid
```

**Comment by ThomasHickman** [comment]
^ is this unexpected output, or are you just verifying that this PR works?

**Comment by mr-c** [comment]
Thanks again @ThomasHickman !

**Pull request merged**
