### PR TITLE
Replace galaxy-lib dependency with galaxy-tool-util.

### LINKED ISSUE #1155: Replace galaxy-lib requirement with galaxy-tool-util
I'm working on Planemo to replace its dependency on galaxy-lib (which will be basically deprecated with Galaxy release 19.09) with [galaxy-tool-util](https://pypi.org/project/galaxy-tool-util/). Unfortunately CWL support in Planemo via cwltool would break unless also cwltool moves to galaxy-tool-util.

I can do the necessary changes in cwltool when I'm back from holidays, in the mean time I wanted to check that's fine with you all.

### PR DESCRIPTION
**Pull request by jmchilton**
galaxy-lib is now unmaintained. We're managing the decomposition of the project from inside of the core codebase to prevent drift.

Fixes #1155

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks so much!

**Comment by jmchilton** [comment]
@mr-c I'd try not to ping you this time of year but I have this paranoid vision of you breaking 2.7 compatibility like at 1am on January 1st as a little treat to yourself to start the decade 😆. If you do do that - just was hoping you'd do a final release that works with 2.7 including this. Thanks and happy new years!

**Comment by nsoranzo** [comment]
@jmchilton I think this is already included in cwltool 1.0.20191225192155 , already on PyPI.

**Comment by jmchilton** [comment]
Crap - browser caching thing maybe, I don't know how I missed that. Sorry for the noise.

**Comment by mr-c** [comment]
@jmchilton No worries, I had started the release process earlier today https://github.com/common-workflow-language/cwltool/releases/tag/1.0.20191225192155

Enjoy!

**Pull request merged**
