### PR TITLE
generating nameroot when not provided explicitly from basename Issue#268

### PR DESCRIPTION
**Pull request by kapilkd13**
When a file is provided in input along with its path and nameroot is not provided, cwltool throws exception. In this PR we are generating nameroot if it is not provide explicitly using basename. Issue #268

### CODE REVIEW

**Comment by kapilkd13** [comment]
Hi, This PR is failing on a unit test. It is generating nameroot field from basename, when a File is specified. But this behavior is expected. After getting your review on it, I would update testcase. Thanks

**Comment by mr-c** [comment]
Thank you @kapilkd13 -- the other place we set the `nameroot` is at https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L154

We need to decide if the duplication is okay, or if this change eliminates the need for the other setting of `nameroot`.

Any thoughts, @tetron ?

**Comment by undu** [comment]
When I execute a workflow with a dir, I get this warning, even though I do not define the "nameroot" field

```
jobs/textures-job.yml:2:3: invalid field `nameroot`, expected one of: 'class', 'location', 'path', 'basename', 'listing'
```

But I have to say the workflow that was blocked by #268 now works. 👍

**Comment by undu** [comment]
The current patch is a bit iffy, when the filename doesn't have an extension it's considered that it has no nameroot.

This is a bit better, but still not good:
```
>>> paths = ['lalala', 'lala.la', 'la.la.la', '.lalala']
>>> [path.rsplit('.', 1) for path in paths]
[['lalala'], ['lala', 'la'], ['la.la', 'la'], ['', 'lalala']]
```

**Comment by kapilkd13** [comment]
Closing this PR. See this [PR](https://github.com/common-workflow-language/cwltool/pull/420) by @undu

**Pull request closed without merging**
