### PR TITLE
test_udocker: Fallback if psutil.tests is missing

### PR DESCRIPTION
**Pull request by jayvdb**
Unix vendors often remove tests from installed packages.
Therefore psutils.tests may be missing, in which case
assume the worst and set TRAVIS = True.

### CODE REVIEW

**Comment by mr-c** [comment]
Hello @jayvdb , which system are you packaging cwltool for?

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by mr-c** [comment]
> Unix vendors often remove tests from installed packages.

If this is the case, then why do you want to patch one of the tests? :-)

**Comment by jayvdb** [comment]
opensuse. https://build.opensuse.org/package/show/devel:languages:python/python-psutil is where psutil.tests is being removed.
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-cwltool is my WIP for getting cwltool packaged.

**Comment by mr-c** [comment]
Thank you @jayvdb !

**Pull request merged**
