### PR TITLE
upload the cwltool-conformance jenkins build script

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by manu-chroma** [comment]
@mr-c I can cherry pick your commit and close this PR?

**Comment by mr-c** [comment]
@manu-chroma Lets merge this first so I can switch the path in the Jenkins config first.

**Comment by manu-chroma** [comment]
We'll have to make ``cwltest`` compatible with Python 3 before we can run py3 conformance on Jenkins.

**Comment by mr-c** [comment]
@manu-chroma I've released `cwltest` version `1.0.20170715115658` with your py3 compat

**Comment by manu-chroma** [comment]
@mr-c is Jenkins now using ``jenkins.bash`` present in the repo to run builds?

**Comment by mr-c** [comment]
@manu-chroma for the main branch yes, not yet for PRs

**Comment by manu-chroma** [comment]
I will update the script once we get it working on the PRs as well. 
Related issue: https://github.com/common-workflow-language/cwltool/issues/471

**Pull request merged**
