### PR TITLE
mypy: don't silence schema_salad errors

### PR DESCRIPTION
**Pull request by manu-chroma**
also, move galaxy stub files from typesheds/2 to typesheds/2and3

### CODE REVIEW

**Comment by mr-c** [comment]
Thanks! Can you also open a PR to donate the galaxylib typehints to the Python Typeshed?

**Comment by manu-chroma** [comment]
I will do that. I'll open an issue on galaxy repo to get their permission and then make the PR. https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library

**Comment by manu-chroma** [comment]
https://github.com/galaxyproject/galaxy/issues/4296

**Comment by mr-c** [comment]
@manu-chroma No need to ask for permission, we obtained it here: https://github.com/common-workflow-language/cwltool/pull/214#issuecomment-313775587 :-)

**Comment by manu-chroma** [comment]
great! :+1:

**Pull request merged**
