### PR TITLE
upgrade to latest schema_salad; misc cleanups

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by Croolis** [comment]
Hi, are you aware that you can simply freeze your requirements versions to avoid braking your library once in a while? It's nice that you have adjusted for upgrade in schema_salad without backward compatibility. But some of the previous versions of cwltool are now forever broken. Don't you want to freeze your dependencies versions in more strict manner to prevent this from happening once again?

**Comment by mr-c** [comment]
Hello @Croolis , you are correct. I'll delete the latest schema_salad release and re-release as a 3.0.x which should fix the problem.

**Comment by Croolis** [comment]
Thank you

**Comment by mr-c** [comment]
Schema_salad 3.0.20181129082112 has been release and the previous release deleted.
and cwltool 1.0.20181129095638 has been released and the previous release deleted.

Thank you for your report and for using cwltool/schema_salad!

**Pull request merged**
