### PR TITLE
10827 static checker fix

### PR DESCRIPTION
**Pull request by lijiayong**
This is a fix to the following bug when the source has linkMerge and sink is "Any". For example,

_echo.cwl_
<pre>
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  echo_in:
    type: Any
    inputBinding: {}
outputs: []
</pre>

_echo-wf.cwl_
<pre>
class: Workflow
cwlVersion: v1.0
requirements:
  MultipleInputFeatureRequirement: {}
inputs:
  letters0:
    type: string
    default: "a0"
  letters1:
    type: string[]
    default: ["a1", "b1"]

outputs: []

steps:
  echo:
    run: echo.cwl
    in:
      echo_in:
        source: [letters0, letters1]
        linkMerge: merge_nested
    out: []
</pre>

Executing the workflow gives the following error.
<pre>
$ cwltool echo-wf.cwl 
/home/jiayong/anaconda2/bin/cwltool 1.0.20170616035942
Resolved 'echo-wf.cwl' to 'file:///home/jiayong/Code/work_scripts/cwl/test/echo_any/echo-wf.cwl'
Tool definition failed validation:
echo-wf.cwl:7:5: Source 'letters0' of type "string" is incompatible
echo-wf.cwl:19:7:   with sink 'echo_in' of type "Any"
echo-wf.cwl:19:7:   sink has linkMerge method merge_nested
echo-wf.cwl:10:5: Source 'letters1' of type {"type": "array", "items": "string"} is incompatible
echo-wf.cwl:19:7:   with sink 'echo_in' of type "Any"
echo-wf.cwl:19:7:   sink has linkMerge method merge_nested
</pre>

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to test list

**Comment by mr-c** [comment]
Jenkins, add to testlist

**Comment by tetron** [comment]
Can you take a look at the bug demonstrated here?  https://github.com/common-workflow-language/common-workflow-language/pull/462

**Comment by lijiayong** [comment]
Sure, looking

**Comment by tetron** [comment]
See also https://github.com/common-workflow-language/cwltool/issues/437

**Comment by lijiayong** [comment]
I think the issue is fixed.

**Pull request merged**
